#!/usr/bin/env python3
"""HERMES FW-08 F2-R1 activated-registry-handle contract v1 (PURE, fixture-backed).

WO-HELM-HERMES-FW08-F2-R1-EXTERNAL-PRODUCER-REGISTRY-ROOT-OF-TRUST-IMPLEMENTATION-0001 (§10 + §11 seal).
Owner: HERMES (Helm). Created (UTC): 2026-07-21. Contract version: 1.

WHY THIS EXISTS (F2-R1). The candidate-readiness path must accept a registry ONLY via an ACTIVATED HANDLE
minted by resolution through a governed external authority boundary — unforgeable by ordinary callers.

STRUCTURAL ANTI-FORGERY (mirrors GovernedEvidenceSealer). `ActivationAuthority` holds an EPHEMERAL,
name-mangled `self.__key` generated by `secrets.token_bytes(32)` — no getter, never serialised, never in
`to_dict`. Only an ActivationAuthority instance can compute (`_seal`) or verify (`verify_handle`) a trusted
seal. A caller can construct an `ActivatedRegistryHandle` directly (it is a frozen dataclass), BUT cannot
produce a valid `seal` without the key — so `is_trusted` rejects it as AH-SEAL-INVALID. THIS is the gate that
makes registry authority non-mintable by ordinary callers.

PURE except the ephemeral seal key (`secrets.token_bytes(32)`), mirroring GovernedEvidenceSealer: no I/O, no
subprocess, no network, stdlib only, deterministic given a fixed key. NOT imported by runtime.
"""
from __future__ import annotations

import dataclasses
import datetime
import hashlib
import hmac
import json
import re
import secrets
from dataclasses import dataclass, field
from typing import Dict, List, Mapping, Optional, Tuple

CONTRACT_VERSION = "1"
_HEX64_RE = re.compile(r"^[0-9a-f]{64}$")
_UTC_ISO_RE = re.compile(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?(\+00:00|Z)$")

CANDIDATE_USE_POLICIES = frozenset({"TEST_ONLY", "REAL_CANDIDATE"})
LIFECYCLE_STATES = frozenset({"ACTIVATED", "UNTRUSTED", "EXPIRED", "REVOKED"})


def _canonical(obj: object) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def _parse_utc(value: str) -> Optional[datetime.datetime]:
    if not isinstance(value, str) or not _UTC_ISO_RE.match(value):
        return None
    try:
        return datetime.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


@dataclass(frozen=True)
class ActivatedRegistryHandle:
    """An activation handle minted by the governed activation flow. `handle_checksum` proves the bound-field
    bytes were not altered; `seal` is the AUTHORITY proof — only an ActivationAuthority key holder can compute
    it. `_bound_registry` carries the live registry object and is EXCLUDED from checksum, seal payload, and
    to_dict (it is the thing the handle grants access to, not part of the sealed identity)."""

    contract_version: str
    application: str
    authority_root_id: str
    authority_root_digest: str
    manifest_id: str
    manifest_digest: str
    registry_id: str
    registry_version: str
    registry_digest: str
    producer_set_digest: str
    activation_utc: str
    validity_end_utc: str
    activation_reason: str
    resolver_identity: str
    resolver_version: str
    resolver_evidence_reference: str
    candidate_use_policy: str            # "TEST_ONLY" / "REAL_CANDIDATE"
    handle_checksum: str
    lifecycle_state: str                 # "ACTIVATED" / "UNTRUSTED" / "EXPIRED" / "REVOKED"
    seal: str                            # hmac hex over bound_fields (ActivationAuthority key)
    _bound_registry: object = field(default=None, repr=False, compare=False)

    def bound_fields(self) -> Dict[str, object]:
        """The sealed projection — the identity fields the checksum + seal cover. EXCLUDES seal,
        handle_checksum, and _bound_registry."""
        return {
            "contract_version": self.contract_version,
            "application": self.application,
            "authority_root_id": self.authority_root_id,
            "authority_root_digest": self.authority_root_digest,
            "manifest_id": self.manifest_id,
            "manifest_digest": self.manifest_digest,
            "registry_id": self.registry_id,
            "registry_version": self.registry_version,
            "registry_digest": self.registry_digest,
            "producer_set_digest": self.producer_set_digest,
            "activation_utc": self.activation_utc,
            "validity_end_utc": self.validity_end_utc,
            "activation_reason": self.activation_reason,
            "resolver_identity": self.resolver_identity,
            "resolver_version": self.resolver_version,
            "resolver_evidence_reference": self.resolver_evidence_reference,
            "candidate_use_policy": self.candidate_use_policy,
            "lifecycle_state": self.lifecycle_state,
        }

    def to_dict(self) -> Dict[str, object]:
        d = dict(self.bound_fields())
        d["handle_checksum"] = self.handle_checksum
        d["seal"] = self.seal
        # _bound_registry and the raw seal key are NEVER serialised.
        return d

    @staticmethod
    def compute_checksum(bound_fields: Mapping[str, object]) -> str:
        return hashlib.sha256(_canonical(dict(bound_fields)).encode("utf-8")).hexdigest()

    def recompute_checksum(self) -> str:
        return ActivatedRegistryHandle.compute_checksum(self.bound_fields())


def _seal_message(handle: ActivatedRegistryHandle) -> bytes:
    """Canonical bytes the seal covers: the handle's bound fields + its checksum."""
    payload = {
        "bound_fields": handle.bound_fields(),
        "handle_checksum": handle.handle_checksum,
    }
    return _canonical(payload).encode("utf-8")


class ActivationAuthority:
    """In-process capability that mints/verifies the activation seal with an EPHEMERAL, never-persisted key.

    Mirrors GovernedEvidenceSealer: the key is generated fresh per instance via `secrets.token_bytes(32)` and
    held ONLY in a name-mangled private attribute. There is NO getter, NO serialisation, and it never enters
    to_dict/logs. A public caller cannot obtain the key, therefore cannot compute a valid seal, therefore
    cannot mint a trusted handle. This is the structural guarantee behind F2-R1."""

    def __init__(self, *, _key: Optional[bytes] = None) -> None:
        # EPHEMERAL activation key — not a persisted credential, never serialised/logged.
        self.__key = _key if _key is not None else secrets.token_bytes(32)

    def _seal(self, payload_bytes: bytes) -> str:
        return hmac.new(self.__key, payload_bytes, hashlib.sha256).hexdigest()

    def verify_handle(self, handle: object) -> bool:
        """Constant-time verification that `handle` carries a seal computed by THIS authority over its own
        bound fields + checksum."""
        if not isinstance(handle, ActivatedRegistryHandle):
            return False
        if not isinstance(handle.seal, str) or not _HEX64_RE.match(handle.seal):
            return False
        expected = self._seal(_seal_message(handle))
        return hmac.compare_digest(expected, handle.seal)


def is_trusted(handle: object, *, activation_authority: object, now_utc: str) -> Tuple[bool, Tuple[str, ...]]:
    """Fail-closed trust test for an activation handle. Returns (ok, sorted reasons). Rejects:
      * not an ActivatedRegistryHandle (incl. a forged handle-shaped Mapping) → AH-WRONG-TYPE;
      * lifecycle_state != 'ACTIVATED' → AH-NOT-ACTIVATED;
      * handle_checksum tamper → AH-CHECKSUM-TAMPER;
      * seal fails activation_authority.verify_handle → AH-SEAL-INVALID (the structural anti-forgery gate: a
        caller-built lookalike with no ActivationAuthority key fails HERE);
      * expired vs now → AH-EXPIRED."""
    reasons: List[str] = []
    if not isinstance(handle, ActivatedRegistryHandle):
        return (False, ("AH-WRONG-TYPE",))
    if not isinstance(activation_authority, ActivationAuthority):
        return (False, ("AH-AUTHORITY-WRONG-TYPE",))
    if handle.lifecycle_state != "ACTIVATED":
        reasons.append("AH-NOT-ACTIVATED")
    if handle.handle_checksum != handle.recompute_checksum():
        reasons.append("AH-CHECKSUM-TAMPER")
    if not activation_authority.verify_handle(handle):
        reasons.append("AH-SEAL-INVALID")
    now = _parse_utc(now_utc)
    end = _parse_utc(handle.validity_end_utc)
    if now is None or end is None or now >= end:
        reasons.append("AH-EXPIRED")
    return (len(reasons) == 0, tuple(sorted(set(reasons))))


def get_bound_registry(handle: object, *, activation_authority: object, now_utc: str):
    """Return the registry bound to `handle` ONLY if `is_trusted`. Otherwise (None, reasons)."""
    ok, reasons = is_trusted(handle, activation_authority=activation_authority, now_utc=now_utc)
    if not ok:
        return (None, reasons)
    return (handle._bound_registry, tuple())
