#!/usr/bin/env python3
"""HMT-2 (real-money checkpoint) — reproduces the v2 corpus-selection manifest from scratch.

Run from the repository root:

    python3 research/hmt2/generate_selection_manifest_v2.py

Pure stdlib + this repository's own `market_truth.acquisition.*` code. Zero network access.
Requires the real reference-series per-session evidence already generated by
`research/hmt2/generate_reference_series_v2.py` (`reference-series-per-session-v2.json`) — does
NOT itself touch the retained native DBN artefacts or make any acquisition call. Running this
script again from the same repository state MUST reproduce the exact same manifest bytes.

v1 (`corpus-selection-manifest-v1.json`) is NEVER modified or regenerated by this script — it
is read only to reconstruct its own selection deterministically (to identify the RANDOM_
DEVELOPMENT/PROTECTED_HOLDOUT sessions to preserve) and to record its own hash as v2's
`superseded_manifest_sha256` lineage pointer.

HMT-2 CORRECTION (this checkpoint, superseding an earlier same-checkpoint uncommitted draft of
this exact script): the earlier draft (a) invalidated PROTECTED_HOLDOUT sessions merely for
colliding with the v2 event snapshot, and invalidated RANDOM_DEVELOPMENT sessions merely for
colliding with the HIGH_VOL_NON_EVENT/COMPRESSION classification outcome — both are exactly the
"replace on mere classification collision" behaviour the architect's brief prohibits; and (b)
treated the raw per-year top/bottom-20% HIGH_VOL_NON_EVENT/COMPRESSION candidate POOLS (~408
sessions each) as the FINAL paid selection, rather than as candidate pools from which a much
smaller (~70) year-stratified sample must be drawn via Hamilton (largest-remainder) allocation +
a deterministic seeded draw. This script fixes both defects. See
`market_truth.acquisition.corpus_selection_v2` module docstring for the corrected precedence
order and reasoning, and `docs/research/hmt2-corpus-selection-methodology-v2.md` / the WO final
report for the full disclosed reasoning behind every judgment call this script makes.

Corrected pipeline order (precedence, highest first):
    1. PROTECTED_HOLDOUT   — preserve v1's 100, replace ONLY for genuine session-invalidity
                             (never for a classification collision). May gain a descriptive,
                             non-stratum-changing `secondary_context` tag.
    2. SCHEDULED_EVENT     — reselected (~80) from the full v2 snapshot, routed around the
                             (now-fixed) PROTECTED_HOLDOUT dates.
    3. RANDOM_DEVELOPMENT  — preserve v1's 50, replace ONLY for genuine session-invalidity or
                             for now being one of the FINAL selected SCHEDULED_EVENT sessions
                             (never for a HIGH_VOL_NON_EVENT/COMPRESSION classification outcome).
                             Backfill (if any) is additionally kept off PROTECTED_HOLDOUT dates
                             (routes around, never displaces).
    4. MATCHED_CONTROL     — one per final selected SCHEDULED_EVENT session, routed around
                             PROTECTED_HOLDOUT and RANDOM_DEVELOPMENT. "No selected catalyst
                             present" is read, as a disclosed judgment call, as "not any date in
                             the full v2 event snapshot" (not merely "not one of the ~80 chosen
                             event sessions") — a control is meant to be a genuinely quiet day,
                             and a real CPI/NFP/PCE/FOMC day that merely wasn't drawn into this
                             corpus's ~80-sample is still not a quiet day in reality.
    5. HIGH_VOL_NON_EVENT  — eligible pool excludes {1,2,3,4}; final ~70 sample drawn via
                             Hamilton year-stratified allocation + deterministic seeded draw
                             (never by log-range magnitude).
    6. COMPRESSION         — same mechanic as #5, against the bottom-20%-within-year pool.

Writes, alongside the manifest itself, a companion evidence file
(`corpus-selection-manifest-v2-allocation-evidence.json`) recording the full Hamilton
allocation tables (year, C_y, raw, floor, remainder, final) for both HIGH_VOL_NON_EVENT and
COMPRESSION, the seed digests used, and the full holdout/random-development
retained/replaced/reason logs — this is genuine evidence the manifest schema itself has no field
for, not a substitute for the manifest's own recorded hash.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS_DIR, "..", ".."))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from market_truth.acquisition import (  # noqa: E402
    HMT2B1_ELIGIBLE_RANGE_START,
    HMT2B1_RESOLVED_FINAL_CUTOFF_DATE,
)
from market_truth.acquisition.corpus_manifest_v2 import (  # noqa: E402
    ManifestMetadataV2,
    ManifestRowV2,
    write_manifest_v2,
)
from market_truth.acquisition.corpus_selection import (  # noqa: E402
    BASE_SHA,
    SELECTION_ALGORITHM_VERSION,
    CORPUS_VERSION,
    STRATUM_PRECEDENCE,
    SEED_DOMAIN_DEVELOPMENT_RANDOM,
    SEED_DOMAIN_PROTECTED_HOLDOUT,
    Stratum,
    TARGET_RANDOM_DEVELOPMENT,
    TARGET_PROTECTED_HOLDOUT,
    deterministic_shuffled_pool,
    domain_seed_hex,
    load_event_records,
    match_controls,
    select_corpus,
    select_scheduled_events,
)
from market_truth.acquisition.corpus_selection_v2 import (  # noqa: E402
    CORPUS_SELECTION_V2_VERSION,
    REASON_NOW_A_SELECTED_SCHEDULED_EVENT_SESSION,
    SEED_DOMAIN_COMPRESSION_V2,
    SEED_DOMAIN_HIGH_VOL_NON_EVENT_V2,
    TARGET_COMPRESSION_V2,
    TARGET_HIGH_VOL_NON_EVENT_V2,
    TARGET_SCHEDULED_EVENT_PER_CLASS_V2,
    build_reselected_event_records,
    group_session_ids_by_year,
    hamilton_apportionment,
    preserve_or_backfill,
    select_final_sample_by_year,
    stratified_scheduled_event_reselection,
)
from market_truth.acquisition.reference_series import (  # noqa: E402
    ReferenceQualityTag,
    SessionReferenceResult,
    select_high_vol_and_compression_candidates,
)
from market_truth.acquisition.session_calendar import CALENDAR_VERSION, build_session_universe  # noqa: E402

# v1's own frozen inputs (unchanged, reproduced here only to identify what to preserve).
V1_CORPUS_START = _dt.date(2017, 5, 21)
V1_CORPUS_CUTOFF = _dt.date(2025, 12, 31)
V1_MANIFEST_PATH = os.path.join(_THIS_DIR, "corpus-selection-manifest-v1.json")
V1_SNAPSHOT_PATH = os.path.join(_THIS_DIR, "scheduled-macro-event-snapshot-v1.json")

# v2's governed range — the same HMT2B1 constants that governed the real acquisitions.
V2_CORPUS_START = _dt.date.fromisoformat(HMT2B1_ELIGIBLE_RANGE_START)
V2_CORPUS_CUTOFF = _dt.date.fromisoformat(HMT2B1_RESOLVED_FINAL_CUTOFF_DATE)
V2_SNAPSHOT_PATH = os.path.join(_THIS_DIR, "scheduled-macro-event-snapshot-v2.json")
V2_REFERENCE_PER_SESSION_PATH = os.path.join(_THIS_DIR, "reference-series-per-session-v2.json")
V2_MANIFEST_OUT_PATH = os.path.join(_THIS_DIR, "corpus-selection-manifest-v2.json")
V2_ALLOCATION_EVIDENCE_OUT_PATH = os.path.join(
    _THIS_DIR, "corpus-selection-manifest-v2-allocation-evidence.json"
)

EVENT_SNAPSHOT_V2_VERSION = "hmt2-scheduled-macro-event-snapshot-v2"


def _sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def _load_v2_reference_results():
    with open(V2_REFERENCE_PER_SESSION_PATH, encoding="utf-8") as f:
        doc = json.load(f)
    results = {}
    reference_snapshot_version = doc["reference_series_version"]
    for r in doc["per_session"]:
        results[r["session_id"]] = SessionReferenceResult(
            session_id=r["session_id"],
            session_date=_dt.date.fromisoformat(r["session_date"]),
            quality_tag=ReferenceQualityTag(r["quality_tag"]),
            session_log_range=r["session_log_range"],
            bar_count=r["bar_count"],
            expected_hour_count=r["expected_hour_count"],
            coverage_ratio=r["coverage_ratio"],
            distinct_instrument_ids=tuple(r["distinct_instrument_ids"]),
        )
    return results, reference_snapshot_version


def _reconstruct_v1_selection():
    """Reproduces v1's exact selection from its own frozen inputs (byte-identical to the
    committed manifest — see the WO final report for the confirming hash check this script's
    caller ran separately). Returns the pieces v2 needs: the four v1 date-sets, and the FULL
    deterministic shuffled pools (not just the drawn `count`) for RANDOM_DEVELOPMENT/
    PROTECTED_HOLDOUT, so v2 can continue those exact sequences."""
    with open(V1_SNAPSHOT_PATH, encoding="utf-8") as f:
        v1_snapshot = json.load(f)
    v1_event_records = load_event_records(v1_snapshot)
    v1_universe = build_session_universe(V1_CORPUS_START, V1_CORPUS_CUTOFF)
    v1_sessions_by_date = {s.session_date: s for s in v1_universe}
    v1_eligible_sorted = sorted(v1_sessions_by_date.keys())

    result_v1 = select_corpus(v1_universe, v1_event_records)

    event_dates_v1 = {row.session.session_date for row in result_v1.scheduled_events}
    control_dates_v1 = {row.session.session_date for row in result_v1.matched_controls}
    random_dates_v1 = sorted(row.session.session_date for row in result_v1.random_development)
    holdout_dates_v1 = sorted(row.session.session_date for row in result_v1.protected_holdout)

    excluded_for_random_v1 = event_dates_v1 | control_dates_v1
    full_pool_random_v1 = deterministic_shuffled_pool(
        v1_eligible_sorted, excluded_for_random_v1, SEED_DOMAIN_DEVELOPMENT_RANDOM
    )
    excluded_for_holdout_v1 = event_dates_v1 | control_dates_v1 | set(random_dates_v1)
    full_pool_holdout_v1 = deterministic_shuffled_pool(
        v1_eligible_sorted, excluded_for_holdout_v1, SEED_DOMAIN_PROTECTED_HOLDOUT
    )

    # Sanity checks — these MUST hold given deterministic_shuffled_pool's contract.
    assert sorted(full_pool_random_v1[:TARGET_RANDOM_DEVELOPMENT]) == random_dates_v1
    assert sorted(full_pool_holdout_v1[:TARGET_PROTECTED_HOLDOUT]) == holdout_dates_v1

    return {
        "random_dates_v1": random_dates_v1,
        "holdout_dates_v1": holdout_dates_v1,
        "full_pool_random_v1": full_pool_random_v1,
        "full_pool_holdout_v1": full_pool_holdout_v1,
    }


def _year_rank_info(reference_results_v2, already_claimed_session_ids, session_date):
    year_rows = sorted(
        (
            r
            for r in reference_results_v2.values()
            if r.session_date.year == session_date.year
            and r.quality_tag == ReferenceQualityTag.REFERENCE_COMPLETE
            and r.session_id not in already_claimed_session_ids
        ),
        key=lambda r: (r.session_log_range, r.session_date),
    )
    ids_in_order = [r.session_id for r in year_rows]
    try:
        rank = ids_in_order.index(
            next(r.session_id for r in year_rows if r.session_date == session_date)
        ) + 1
    except StopIteration:
        return None, None, None
    n = len(year_rows)
    percentile = rank / n if n else None
    return rank, n, percentile


def _allocation_table(allocation) -> list:
    return [
        {
            "year": a.year,
            "candidate_count": a.candidate_count,
            "raw_allocation": a.raw_allocation,
            "floor_allocation": a.floor_allocation,
            "remainder": a.remainder,
            "final_allocation": a.final_allocation,
        }
        for a in allocation.per_year
    ]


def main() -> None:
    superseded_sha256 = _sha256_file(V1_MANIFEST_PATH)
    with open(V1_MANIFEST_PATH, encoding="utf-8") as f:
        v1_document = json.load(f)
    v1_recorded_manifest_sha256 = v1_document["manifest_sha256"]

    v1_pieces = _reconstruct_v1_selection()

    with open(V2_SNAPSHOT_PATH, encoding="utf-8") as f:
        v2_snapshot = json.load(f)
    event_records_v2_full = load_event_records(v2_snapshot)
    full_v2_event_dates = {e.date for e in event_records_v2_full}
    events_by_date_v2_full: dict = {}
    for e in event_records_v2_full:
        events_by_date_v2_full.setdefault(e.date, set()).add(e.event_class)

    v2_universe = build_session_universe(V2_CORPUS_START, V2_CORPUS_CUTOFF)
    sessions_by_date_v2 = {s.session_date: s for s in v2_universe}
    valid_session_dates_v2 = set(sessions_by_date_v2.keys())

    # ---- Step 1: PROTECTED_HOLDOUT (top precedence, decided first) — preserve v1's 100,
    #      replace ONLY for genuine session-invalidity. `invalid_if_in` is DELIBERATELY empty:
    #      a holdout session is never displaced merely for colliding with another stratum's
    #      classification (event snapshot, high-vol/compression, anything). ----
    holdout_result = preserve_or_backfill(
        original_v1_dates=v1_pieces["holdout_dates_v1"],
        full_v1_shuffled_pool=v1_pieces["full_pool_holdout_v1"],
        invalid_if_in=set(),
        already_used_for_backfill=set(),
        valid_session_dates=valid_session_dates_v2,
        target_count=TARGET_PROTECTED_HOLDOUT,
    )
    holdout_dates_v2 = set(holdout_result.final_dates)

    # Descriptive-only secondary_context: does this holdout date happen to coincide with a
    # scheduled macro-event date in the full v2 snapshot? Never changes primary_stratum.
    holdout_secondary_context = {
        d: "+".join(sorted(events_by_date_v2_full[d])) for d in holdout_dates_v2 if d in events_by_date_v2_full
    }

    # ---- Step 2: SCHEDULED_EVENT reselection, routed around the (now-fixed) holdout dates ----
    reselection = stratified_scheduled_event_reselection(
        event_records_v2_full,
        sessions_by_date_v2,
        target_per_class=TARGET_SCHEDULED_EVENT_PER_CLASS_V2,
        exclude_dates=frozenset(holdout_dates_v2),
    )
    filtered_event_records_v2 = build_reselected_event_records(
        event_records_v2_full, reselection.chosen_class_date_pairs
    )
    selected_events_v2 = select_scheduled_events(filtered_event_records_v2, sessions_by_date_v2)
    event_dates_v2 = {row.session.session_date for row in selected_events_v2}
    assert event_dates_v2.isdisjoint(holdout_dates_v2), "SCHEDULED_EVENT must never displace PROTECTED_HOLDOUT"

    # ---- Step 3: RANDOM_DEVELOPMENT — preserve v1's 50; replace ONLY for genuine
    #      session-invalidity or for now being a FINAL selected SCHEDULED_EVENT session (the
    #      brief's two named reasons for this stratum). NEVER for a HIGH_VOL_NON_EVENT/
    #      COMPRESSION classification outcome — that set is not even computed yet at this point
    #      in the pipeline, by construction, so it cannot leak in. Backfill additionally avoids
    #      (without inventing a third invalidation "reason") PROTECTED_HOLDOUT dates, since
    #      RANDOM_DEVELOPMENT must route around holdout, never displace or duplicate it. ----
    random_result = preserve_or_backfill(
        original_v1_dates=v1_pieces["random_dates_v1"],
        full_v1_shuffled_pool=v1_pieces["full_pool_random_v1"],
        invalid_if_in=event_dates_v2,
        already_used_for_backfill=event_dates_v2 | holdout_dates_v2,
        valid_session_dates=valid_session_dates_v2,
        target_count=TARGET_RANDOM_DEVELOPMENT,
        collision_reason=REASON_NOW_A_SELECTED_SCHEDULED_EVENT_SESSION,
    )
    random_dates_v2 = set(random_result.final_dates)
    assert random_dates_v2.isdisjoint(holdout_dates_v2), "RANDOM_DEVELOPMENT must never displace PROTECTED_HOLDOUT"
    assert random_dates_v2.isdisjoint(event_dates_v2), "RANDOM_DEVELOPMENT must never displace SCHEDULED_EVENT"

    # ---- Step 4: MATCHED_CONTROL — one per final selected SCHEDULED_EVENT session. "No
    #      selected catalyst present" is read (disclosed judgment call — see module docstring)
    #      as "absent from the FULL v2 event snapshot", plus routed around PROTECTED_HOLDOUT and
    #      RANDOM_DEVELOPMENT (never displacing either). ----
    matched_controls_v2, unmatched_v2 = match_controls(
        selected_events_v2, sessions_by_date_v2, full_v2_event_dates | holdout_dates_v2 | random_dates_v2
    )
    control_dates_v2 = {row.session.session_date for row in matched_controls_v2}
    assert control_dates_v2.isdisjoint(holdout_dates_v2 | random_dates_v2 | event_dates_v2)

    # ---- Step 5/6: HIGH_VOL_NON_EVENT / COMPRESSION — eligible pool excludes everything claimed
    #      by strata 1-4; final ~70 sample per stratum drawn via Hamilton year-stratified
    #      allocation + a deterministic domain-separated seeded draw (never by log-range
    #      magnitude within the pool). ----
    reference_results_v2, reference_snapshot_version = _load_v2_reference_results()
    already_claimed_dates_for_refseries = event_dates_v2 | control_dates_v2 | holdout_dates_v2 | random_dates_v2
    already_claimed_session_ids_for_refseries = {
        sessions_by_date_v2[d].session_id for d in already_claimed_dates_for_refseries if d in sessions_by_date_v2
    }
    high_vol_pool_ids, compression_pool_ids = select_high_vol_and_compression_candidates(
        reference_results_v2, already_claimed_session_ids_for_refseries
    )

    high_vol_pool_by_year = group_session_ids_by_year(high_vol_pool_ids, reference_results_v2)
    compression_pool_by_year = group_session_ids_by_year(compression_pool_ids, reference_results_v2)
    high_vol_counts_by_year = {y: len(ids) for y, ids in high_vol_pool_by_year.items()}
    compression_counts_by_year = {y: len(ids) for y, ids in compression_pool_by_year.items()}

    high_vol_allocation = hamilton_apportionment(high_vol_counts_by_year, TARGET_HIGH_VOL_NON_EVENT_V2)
    compression_allocation = hamilton_apportionment(compression_counts_by_year, TARGET_COMPRESSION_V2)

    high_vol_final_ids = select_final_sample_by_year(
        high_vol_pool_by_year, high_vol_allocation, SEED_DOMAIN_HIGH_VOL_NON_EVENT_V2
    )
    compression_final_ids = select_final_sample_by_year(
        compression_pool_by_year, compression_allocation, SEED_DOMAIN_COMPRESSION_V2
    )
    high_vol_dates = {reference_results_v2[sid].session_date for sid in high_vol_final_ids}
    compression_dates = {reference_results_v2[sid].session_date for sid in compression_final_ids}

    # ---- Sanity: zero duplicate assignment across any stratum ----
    all_claimed = [event_dates_v2, control_dates_v2, holdout_dates_v2, high_vol_dates, compression_dates, random_dates_v2]
    seen = set()
    for group in all_claimed:
        assert seen.isdisjoint(group), "duplicate session assignment detected across v2 strata"
        seen |= group

    # ---- Assemble rows ----
    rows: list[ManifestRowV2] = []

    def _base_kwargs(session, primary_stratum, protected_holdout, inclusion_reason, secondary_context=None):
        return dict(
            corpus_version=CORPUS_VERSION,
            session_id=session.session_id,
            gc_trade_date=session.session_date.isoformat(),
            request_start_utc=session.window_start_utc.isoformat(),
            request_end_utc=session.window_end_utc.isoformat(),
            primary_stratum=primary_stratum,
            protected_holdout=protected_holdout,
            selection_algorithm_version=CORPUS_SELECTION_V2_VERSION,
            calendar_version=session.calendar_version,
            inclusion_reason=inclusion_reason,
            secondary_context=secondary_context,
        )

    for row in selected_events_v2:
        rows.append(ManifestRowV2(
            **_base_kwargs(row.session, Stratum.SCHEDULED_EVENT.value, False, row.inclusion_reason),
            event_class=row.event_class, event_source_ref=row.event_source_ref,
            event_snapshot_version=EVENT_SNAPSHOT_V2_VERSION,
        ))

    for row in matched_controls_v2:
        rows.append(ManifestRowV2(
            **_base_kwargs(row.session, Stratum.MATCHED_CONTROL.value, False, row.inclusion_reason),
            matched_parent_session=row.matched_parent_session,
            event_snapshot_version=EVENT_SNAPSHOT_V2_VERSION,
        ))

    for sid in high_vol_final_ids:
        r = reference_results_v2[sid]
        session = sessions_by_date_v2[r.session_date]
        rank, n, pct = _year_rank_info(reference_results_v2, already_claimed_session_ids_for_refseries, r.session_date)
        rows.append(ManifestRowV2(
            **_base_kwargs(session, Stratum.HIGH_VOL_NON_EVENT.value, False,
                            "hamilton_year_stratified_seeded_draw_from_top_20pct_within_year_pool"),
            session_log_range=r.session_log_range, reference_quality=r.quality_tag.value,
            within_year_rank=rank, within_year_eligible_count=n, within_year_percentile=pct,
            continuous_underlying_instrument_ids=r.distinct_instrument_ids,
            reference_snapshot_version=reference_snapshot_version,
        ))

    for sid in compression_final_ids:
        r = reference_results_v2[sid]
        session = sessions_by_date_v2[r.session_date]
        rank, n, pct = _year_rank_info(reference_results_v2, already_claimed_session_ids_for_refseries, r.session_date)
        rows.append(ManifestRowV2(
            **_base_kwargs(session, Stratum.COMPRESSION.value, False,
                            "hamilton_year_stratified_seeded_draw_from_bottom_20pct_within_year_pool"),
            session_log_range=r.session_log_range, reference_quality=r.quality_tag.value,
            within_year_rank=rank, within_year_eligible_count=n, within_year_percentile=pct,
            continuous_underlying_instrument_ids=r.distinct_instrument_ids,
            reference_snapshot_version=reference_snapshot_version,
        ))

    for d in sorted(random_dates_v2):
        session = sessions_by_date_v2[d]
        preserved = d in random_result.kept_dates
        reason = "preserved_from_v1_random_development_draw" if preserved else "v2_backfilled_random_development_draw_continuation"
        lineage = None if preserved else "replaces_an_invalidated_v1_random_development_session;draw_continuation_index"
        rows.append(ManifestRowV2(
            **_base_kwargs(session, Stratum.RANDOM_DEVELOPMENT.value, False, reason),
            random_seed_domain=SEED_DOMAIN_DEVELOPMENT_RANDOM, random_seed_version=CORPUS_SELECTION_V2_VERSION,
            exclusion_or_replacement_lineage=lineage,
        ))

    for d in sorted(holdout_dates_v2):
        session = sessions_by_date_v2[d]
        preserved = d in holdout_result.kept_dates
        reason = "preserved_from_v1_protected_holdout_draw" if preserved else "v2_backfilled_protected_holdout_draw_continuation"
        lineage = None if preserved else "replaces_an_invalidated_v1_protected_holdout_session;draw_continuation_index"
        rows.append(ManifestRowV2(
            **_base_kwargs(
                session, Stratum.PROTECTED_HOLDOUT.value, True, reason,
                secondary_context=holdout_secondary_context.get(d),
            ),
            random_seed_domain=SEED_DOMAIN_PROTECTED_HOLDOUT, random_seed_version=CORPUS_SELECTION_V2_VERSION,
            exclusion_or_replacement_lineage=lineage,
        ))

    rows.sort(key=lambda r: r.session_id)

    for u in unmatched_v2:
        print(f"UNMATCHED EVENT (documented, not fabricated): {u}", file=sys.stderr)
    for d in holdout_result.invalidated_dates:
        print(f"INVALIDATED v1 PROTECTED_HOLDOUT session GC-{d.isoformat()}: {holdout_result.invalidation_reasons[d]}", file=sys.stderr)
    for d in random_result.invalidated_dates:
        print(f"INVALIDATED v1 RANDOM_DEVELOPMENT session GC-{d.isoformat()}: {random_result.invalidation_reasons[d]}", file=sys.stderr)

    metadata = ManifestMetadataV2(
        corpus_version=CORPUS_VERSION,
        manifest_schema_version="hmt2-corpus-selection-manifest-v2",
        selection_algorithm_version=CORPUS_SELECTION_V2_VERSION,
        calendar_version=CALENDAR_VERSION,
        session_universe_start=V2_CORPUS_START.isoformat(),
        session_universe_end=V2_CORPUS_CUTOFF.isoformat(),
        seed_development_random_hex=domain_seed_hex(SEED_DOMAIN_DEVELOPMENT_RANDOM),
        seed_protected_holdout_hex=domain_seed_hex(SEED_DOMAIN_PROTECTED_HOLDOUT),
        stratum_precedence_order=tuple(s.value for s in STRATUM_PRECEDENCE),
        superseded_manifest_relative_path="research/hmt2/corpus-selection-manifest-v1.json",
        superseded_manifest_sha256=v1_recorded_manifest_sha256,
        event_snapshot_version=EVENT_SNAPSHOT_V2_VERSION,
        reference_snapshot_version=reference_snapshot_version,
        generated_by="research/hmt2/generate_selection_manifest_v2.py",
        base_sha=BASE_SHA,
        notes=(
            "HMT-2 real-money checkpoint (CORRECTED). SCHEDULED_EVENT deterministically "
            f"reselected (~{TARGET_SCHEDULED_EVENT_PER_CLASS_V2} per class, spread across years) "
            "from the now-complete v2 event snapshot, routed around PROTECTED_HOLDOUT. "
            "PROTECTED_HOLDOUT/RANDOM_DEVELOPMENT preserve v1's exact sessions with near-zero "
            "churn — replacement occurs ONLY for genuine session-invalidity (holdout) or genuine "
            "session-invalidity/now-a-selected-event-session (random-development); NEVER for a "
            "mere classification collision. HIGH_VOL_NON_EVENT/COMPRESSION are computed from the "
            "real, retained GC.v.0 ohlcv-1h reference series: a raw per-year top/bottom-20% "
            "candidate POOL is first excluded of everything claimed by strata 1-4, then reduced "
            "to a final ~70-session, year-stratified sample via Hamilton (largest-remainder) "
            "allocation plus a deterministic domain-separated seeded draw (never by log-range "
            "magnitude) — see corpus-selection-manifest-v2-allocation-evidence.json for the full "
            "allocation tables and seed digests, and stderr output / WO final report for exactly "
            "which RANDOM_DEVELOPMENT/PROTECTED_HOLDOUT sessions changed and why. Precedence "
            "order for v2 (see corpus_selection_v2 module docstring): PROTECTED_HOLDOUT > "
            "SCHEDULED_EVENT > RANDOM_DEVELOPMENT > MATCHED_CONTROL > HIGH_VOL_NON_EVENT > "
            "COMPRESSION — RANDOM_DEVELOPMENT is HIGHER precedence than MATCHED_CONTROL/"
            "HIGH_VOL_NON_EVENT/COMPRESSION in v2, unlike v1."
        ),
    )

    digest = write_manifest_v2(V2_MANIFEST_OUT_PATH, metadata, rows)

    counts = {}
    for r in rows:
        counts[r.primary_stratum] = counts.get(r.primary_stratum, 0) + 1
    secondary_tag_count = sum(1 for r in rows if r.secondary_context)

    allocation_evidence = {
        "version": "hmt2-corpus-selection-v2-allocation-evidence-v1",
        "manifest_sha256": digest,
        "base_sha": BASE_SHA,
        "high_vol_non_event": {
            "seed_domain": SEED_DOMAIN_HIGH_VOL_NON_EVENT_V2,
            "seed_domain_sha256": domain_seed_hex(SEED_DOMAIN_HIGH_VOL_NON_EVENT_V2),
            "target_total": TARGET_HIGH_VOL_NON_EVENT_V2,
            "total_candidates_in_pool": high_vol_allocation.total_candidates,
            "shortfall": high_vol_allocation.shortfall,
            "final_total": high_vol_allocation.final_total,
            "allocation_table": _allocation_table(high_vol_allocation),
        },
        "compression": {
            "seed_domain": SEED_DOMAIN_COMPRESSION_V2,
            "seed_domain_sha256": domain_seed_hex(SEED_DOMAIN_COMPRESSION_V2),
            "target_total": TARGET_COMPRESSION_V2,
            "total_candidates_in_pool": compression_allocation.total_candidates,
            "shortfall": compression_allocation.shortfall,
            "final_total": compression_allocation.final_total,
            "allocation_table": _allocation_table(compression_allocation),
        },
        "protected_holdout": {
            "kept": len(holdout_result.kept_dates),
            "invalidated": len(holdout_result.invalidated_dates),
            "backfilled": len(holdout_result.backfilled_dates),
            "invalidation_log": [
                {"session_date": d.isoformat(), "reason": holdout_result.invalidation_reasons[d]}
                for d in holdout_result.invalidated_dates
            ],
        },
        "random_development": {
            "kept": len(random_result.kept_dates),
            "invalidated": len(random_result.invalidated_dates),
            "backfilled": len(random_result.backfilled_dates),
            "invalidation_log": [
                {"session_date": d.isoformat(), "reason": random_result.invalidation_reasons[d]}
                for d in random_result.invalidated_dates
            ],
        },
        "primary_stratum_counts": counts,
        "total_unique_sessions": len(rows),
        "secondary_context_tag_count": secondary_tag_count,
        "unmatched_event_count": len(unmatched_v2),
    }
    with open(V2_ALLOCATION_EVIDENCE_OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(allocation_evidence, f, indent=2, sort_keys=True)
        f.write("\n")

    print(f"Wrote manifest: {V2_MANIFEST_OUT_PATH}")
    print(f"manifest_sha256: {digest}")
    print(f"superseded (v1) manifest_sha256: {v1_recorded_manifest_sha256}")
    print(f"counts: {counts}")
    print(f"total rows: {len(rows)}")
    print(f"secondary_context tag count: {secondary_tag_count}")
    print(f"holdout kept={len(holdout_result.kept_dates)} invalidated={len(holdout_result.invalidated_dates)} backfilled={len(holdout_result.backfilled_dates)}")
    print(f"random-dev kept={len(random_result.kept_dates)} invalidated={len(random_result.invalidated_dates)} backfilled={len(random_result.backfilled_dates)}")
    print(f"unmatched events: {len(unmatched_v2)}")
    print(f"wrote allocation evidence: {V2_ALLOCATION_EVIDENCE_OUT_PATH}")


if __name__ == "__main__":
    main()
